import os

from seeds.schema.result import SeedsResult


def save_seeds_result(result: SeedsResult, scenario: str):
    """
    Saves SeedsResult into a JSON-file.

    :param result: Seeding result generated by seeding builder.
    :param scenario: Load test scenario name for which the data is generated.
                     Used to generate JSON-file name (i.e., 'credit_card_test').
    """
    # Make sure that `dumps` directory exists
    if not os.path.exists('dumps'):
        os.mkdir('dumps')

    with open(f'./dumps/{scenario}_seeds.json', 'w+', encoding='utf-8') as file:
        file.write(result.model_dump_json())


def load_seeds_result(scenario: str) -> SeedsResult:
    """
    Loads seeding result from a JSON-file.

    :param scenario: Load test scenario name for which the data needs to be loaded.
    :return: SeedsResult object restored from the file.
    """
    with open(f'./dumps/{scenario}_seeds.json', 'r', encoding="utf-8") as file:
        return SeedsResult.model_validate_json(file.read())
